### ISSUE TITLE
Linux Kernel Source Code

### ISSUE THREAD

**Issue by smallpotato000** [retrofw/firmware#7]
The linux kernel came with RetroFW is 2.6.31.3. I cannot find source code & configs for this.
P.S. is there any working port of 3.x or 4.x to RS97 & LDK?

**Comment by gameblabla** [comment]
I can tell you that you won't get any answers from Pingflood, even though he has a slightly updated kernel & uboot source code.
He has been very uncooperative with anyone asking for the kernel source code (saying that buildroot is the kernel source code, what a moron)

I leaked the kernel code here :
https://github.com/rs-97-cfw/rs97-linux-kernel-NoNDA

I had to remove jz4760_ipu.c though because it was under an NDA prohibiting source code release.
(They did release an IPU code for 2.6.32 and i have that one as well but it's completely different)

Also, except for getting USB to work, i could only get it to work as far as 2.6.35. 2.6.36 and you won't get any sounds and 2.6.38 has removed BLK, which the sound code depends on.
So if you are thinking of porting the source code to 3.x or even upstream 5.3 then you will have to base it upon the source code and pcerceui's Opendingux kernel source.

Cheers

**Comment by gameblabla** [comment]
I can tell you that you won't get any answers from Pingflood, even though he has a slightly updated kernel & uboot source code.
He has been very uncooperative with anyone asking for the kernel source code (saying that buildroot is the kernel source code, really...)

I leaked the kernel code here :
https://github.com/rs-97-cfw/rs97-linux-kernel-NoNDA

I had to remove jz4760_ipu.c though because it was under an NDA prohibiting source code release.
(They did release an IPU code for 2.6.32 and i have that one as well but it's completely different)

Also, except for getting USB to work, i could only get it to work as far as 2.6.35. 2.6.36 and you won't get any sounds and 2.6.38 has removed BLK, which the sound code depends on.
So if you are thinking of porting the source code to 3.x or even upstream 5.3 then you will have to base it upon the source code and pcerceui's Opendingux kernel source.
See https://github.com/OpenDingux/linux if you want to check out how pcerceui ported it to the RS-90, it should be a good base.

Cheers

**Comment by pingflood** [comment]
@gameblabla considering that you are a _very cooperative_ person and that you have exactly the same kernel sources as I had access, how about stop whining and do all the improvements you want and release the full kernel sources for everyone?

**Comment by gameblabla** [comment]
> you have exactly the same kernel sources as I had access
What about support for the IPS display in the RS-97 anniversary edition ? Tony was working on adding support for it at some point. I would think he gave it to you but looks like not ?

As for improvements, well that's up to him if he wants to work on it, i'm not interested.

**Comment by pingflood** [comment]
> As for improvements, well that's up to him if he wants to work on it, i'm not interested.

Of course you are not interested in any improvements. You just want to troll, offend and poison the community.

> Also i know that you have uboot source code, which i don't. If you really want to do the good & nice thing and me to apologize, then you know what to do.

LOL! You are a joke and makes me laugh. XD XD

> Did you see me whining?

All.the.time. That's all that you do and that's what you are. ;)

**Comment by gameblabla** [comment]
> Of course you are not interested in any improvements. You just want to troll, offend and poison the community.

No, i don't want to work on it anymore because of your behaviour and the fact you would refuse to cooperate with me, ever since you refuse to share GMenuNx's source code since January or so.
(You would always remain silent when i asked about it)
I'm also not well versed when it comes to kernel hacking... which is the reason why i said so.
Yes, i'm not perfect i admit it.

Tony decided for no clear reasons to remove me from the linux bitbucket repo. I barely talked to him at all. When i started to throw accusations of you not complying with software licenses (that included ReGBA), you all did is laugh at me and try to put the blame on me.

Others asked you for the kernel & uboot source code and you redirected them to buildroot, which is not the same thing. You are very well aware it's not the same thing ?
I am not interested in trolling, what i am interested is code. You call me a troll yet you would still do forks of emulators and modification that i did on your very own repository. (NGPCemu, SMS Plus GX, SwanEmu, blockout2 and so on. All of which required tons of hours of working on my part)

I would be one kind of a special troll to actively work on improving & porting emulators !
I'm not saying that you did not do anything either way, i have to give credit where it's due but clearly that answer from you (and the fact that GmenuNx's source code was never updated since October 2018) is precisely why i do not condone your behaviour & actions in the course of things.

It's a fact : uboot is GPLv2 licensed. I've had people tell me you made builds of uboot for them.
There are binary builds of uboot for each revision in RetroFW.
Yet you still deny it and put the blame on me.

And yes, i did complain at other times, like the fact that PocketSNES was not profiled and the end result was whining from users complaining about it not running well. I was only trying to prevent this but you not sharing your work (or only much later) was making things difficult and it's why i had to "whine".

So again, what are you going to do ? Paint me as troll and do nothing or release uboot's source code ?
If you really want people to trust your painting of me as a troll, then why not just do it ?

**Comment by pingflood** [comment]
Fixed here: https://github.com/retrofw/kernel/commit/b2cf0330c2e0bdb4bf84e9eaab6b2f3d9afe0764
